### ISSUE TITLE
Detailed debugging instructions

### ISSUE THREAD

**Issue by JimmyLaessig** [Esri/esri-cityengine-sdk#33]
Hello there, 
I'm interested in creating a custom exporter for CE2018 and was wondering if there#s more information on how to achieve step-by-step debugging using Visual Studio or an equivalent. 

I'm able to compile it using the proposed cmake & nmake steps. I also am able to compile and run the encoder with DCMAKE-BUILD_TYPE=RelWithDebInfo. Running with DCMAKE_BUILD_TYPE=Debug compiles but CityEngine does not recognize the exporter. 

Thanks in advance!

**Comment by mistafunk** [comment]
On Windows, debug builds of custom encoders are not recognized by CityEngine because they are not ABI compatible with PRT's C++ extension interface (one cannot mix msvc Release and Debug builds).

We recommend to use RelWithDebInfo and disable the optimization, i.e. `-O0`, this should give you accurate line numbers.

I've logged an internal ticket to improve the documentation in this regard, thanks.

**Comment by JimmyLaessig** [comment]
Thank you for the quick reply. I'm currently testing development with Visual Studio Code and gdb debugger.

**Comment by mistafunk** [comment]
Ok for you if we close this issue?
